export interface ContratoInterface {
  salario_id?: any;
  id?: number;
  fechaContratacion: any;
  horaSistema?: string;
  perfilProfesional: string;
  otrosi: string;
  periodoPago?: string;
  idpersona?: number;
  idtipoContrato: string;
  fechaSistema: string;
  observacion: string;
  fechaFinalContrato: any;
  valorTotalContrato: string;
  objetoContrato: string;
  sueldo: string;
  rol: any;
  idPension?: string;
  idSalud?: string;
  idArl?: string;
  idCajaCompensacion?: string;
  idCesantias?: string;
  tipoCuentaBancaria?: string;
  idBanco?: string;
  numeroCuentaBancaria?: string;
  observacionPreocupacional?: string;
  idArea?: string;
  tipoCotizante ?: string;
  tipoComisiones?: string;
}
